# Generated by Django 5.1 on 2024-10-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Chef',
        ),
    ]
