# Generated by Django 5.1 on 2024-10-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_rename_category_chef'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chef',
            new_name='Try',
        ),
    ]
